spring:
  cloud:
      consul:
           host: localhost
           port: 8500
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb/usermodule?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Balaji@407
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
             hibernate:
                     dialect: org.hibernate.dialect.MySQL8Dialect
     
management:
        endpoints:
                jmx:
                   exposure: 
                          include : "*"


 
