spring:
  cloud:
      consul:
           host: localhost
           port: 8500
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:host.docker.internal}:3306/usermodule?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${username}
    password: ${password}
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
             hibernate:
                     dialect: org.hibernate.dialect.MySQL8Dialect 


 
